apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql-dvdrental.fullname" . }}
  labels:
    {{- include "postgresql-dvdrental.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: psql
      protocol: TCP
      name: psql
  selector:
    {{- include "postgresql-dvdrental.selectorLabels" . | nindent 4 }}
